CREATE TYPE "InstanceConnectionStatus" AS ENUM ('ONLINE', 'OFFLINE');
CREATE TYPE "DeviceMessage" AS ENUM ('ios', 'android', 'web', 'unknown', 'desktop');

CREATE TABLE "Instance" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(255) UNIQUE NOT NULL,
    "description" varchar(255),
    "connectionStatus" "InstanceConnectionStatus" NOT NULL DEFAULT 'OFFLINE',
    "ownerJid" varchar(100),
    "profilePicUrl" varchar(500),
    "createdAt" timestamp NOT NULL DEFAULT now(),
    "updatedAt" timestamp NOT NULL DEFAULT now(),
    "externalAttributes" json
);

CREATE TABLE "Auth" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "token" text UNIQUE NOT NULL,
    "createdAt" timestamp NOT NULL DEFAULT now(),
    "updatedAt" timestamp NOT NULL DEFAULT now(),
    "instanceId" integer UNIQUE NOT NULL REFERENCES "Instance" ("id") ON DELETE CASCADE
);

CREATE TABLE "Message" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "keyId" varchar(100) NOT NULL,
    "keyRemoteJid" varchar(100),
    "keyLid" varchar(100),
    "keyFromMe" boolean NOT NULL,
    "keyParticipant" varchar(100),
    "keyParticipantLid" varchar(100),
    "pushName" varchar(100),
    "messageType" varchar(100) NOT NULL,
    "content" jsonb NOT NULL,
    "messageTimestamp" integer NOT NULL,
    "device" "DeviceMessage" NOT NULL,
    "isGroup" boolean,
    "instanceId" integer NOT NULL REFERENCES "Instance" ("id") ON DELETE CASCADE
);

CREATE TABLE "MessageUpdate" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dateTime" timestamp NOT NULL,
    "status" varchar(30) NOT NULL,
    "messageId" integer NOT NULL REFERENCES "Message" ("id") ON DELETE CASCADE
);

CREATE TABLE "Chat" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "remoteJid" varchar(100) NOT NULL,
    "content" jsonb,
    "createdAt" timestamp NOT NULL DEFAULT now(),
    "updatedAt" timestamp NOT NULL DEFAULT now(),
    "instanceId" integer NOT NULL REFERENCES "Instance" ("id") ON DELETE CASCADE
);

CREATE TABLE "Contact" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "remoteJid" varchar(100) NOT NULL,
    "pushName" varchar(100),
    "profilePicUrl" varchar(500),
    "createdAt" timestamp NOT NULL DEFAULT now(),
    "updatedAt" timestamp NOT NULL DEFAULT now(),
    "instanceId" integer NOT NULL REFERENCES "Instance" ("id") ON DELETE CASCADE
);

CREATE TABLE "Webhook" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "url" varchar(500) NOT NULL,
    "enabled" boolean NOT NULL DEFAULT true,
    "events" jsonb,
    "createdAt" timestamp NOT NULL DEFAULT now(),
    "updatedAt" timestamp NOT NULL DEFAULT now(),
    "instanceId" integer UNIQUE NOT NULL REFERENCES "Instance" ("id") ON DELETE CASCADE
);

CREATE INDEX "Message_keyId_idx" ON "Message" ("keyId");
CREATE INDEX "Message_instanceId_id_idx" ON "Message" ("instanceId", "id");
CREATE INDEX "Message_instanceId_keyRemoteJid_idx" ON "Message" ("instanceId", "keyRemoteJid");
CREATE INDEX "Message_instanceId_keyFromMe_idx" ON "Message" ("instanceId", "keyFromMe");
CREATE INDEX "Message_instanceId_messageType_idx" ON "Message" ("instanceId", "messageType");
CREATE INDEX "Message_instanceId_device_idx" ON "Message" ("instanceId", "device");
CREATE INDEX "Message_instanceId_messageTimestamp_idx" ON "Message" ("instanceId", "messageTimestamp");
CREATE INDEX "MessageUpdate_messageId_status_idx" ON "MessageUpdate" ("messageId", "status");
CREATE INDEX "MessageUpdate_messageId_dateTime_id_idx" ON "MessageUpdate" ("messageId", "dateTime", "id");
CREATE INDEX "Chat_instanceId_id_idx" ON "Chat" ("instanceId", "id");
CREATE INDEX "Contact_instanceId_id_idx" ON "Contact" ("instanceId", "id");
