// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: address_mapping.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAddressMappingByCanonicalJID = `-- name: DeleteAddressMappingByCanonicalJID :execrows
DELETE FROM "WhatsAppAddressMapping"
WHERE "instanceId" = $1
  AND "canonicalJid" = $2
`

type DeleteAddressMappingByCanonicalJIDParams struct {
	Instanceid   int32  `json:"instanceid"`
	Canonicaljid string `json:"canonicaljid"`
}

func (q *Queries) DeleteAddressMappingByCanonicalJID(ctx context.Context, arg DeleteAddressMappingByCanonicalJIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAddressMappingByCanonicalJID, arg.Instanceid, arg.Canonicaljid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAddressMappingByAlias = `-- name: FindAddressMappingByAlias :one
SELECT "instanceId", alias, "normalizedPhone", "canonicalJid", "lidJid", "resolvedAt", "expiresAt", "createdAt", "updatedAt"
FROM "WhatsAppAddressMapping"
WHERE "instanceId" = $1
  AND "alias" = $2
LIMIT 1
`

type FindAddressMappingByAliasParams struct {
	Instanceid int32  `json:"instanceid"`
	Alias      string `json:"alias"`
}

func (q *Queries) FindAddressMappingByAlias(ctx context.Context, arg FindAddressMappingByAliasParams) (WhatsAppAddressMapping, error) {
	row := q.db.QueryRow(ctx, findAddressMappingByAlias, arg.Instanceid, arg.Alias)
	var i WhatsAppAddressMapping
	err := row.Scan(
		&i.InstanceId,
		&i.Alias,
		&i.NormalizedPhone,
		&i.CanonicalJid,
		&i.LidJid,
		&i.ResolvedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAddressMappingAliases = `-- name: ListAddressMappingAliases :many
SELECT "alias"
FROM "WhatsAppAddressMapping"
WHERE "instanceId" = $1
  AND "canonicalJid" = $2
ORDER BY "alias"
`

type ListAddressMappingAliasesParams struct {
	Instanceid   int32  `json:"instanceid"`
	Canonicaljid string `json:"canonicaljid"`
}

func (q *Queries) ListAddressMappingAliases(ctx context.Context, arg ListAddressMappingAliasesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listAddressMappingAliases, arg.Instanceid, arg.Canonicaljid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var alias string
		if err := rows.Scan(&alias); err != nil {
			return nil, err
		}
		items = append(items, alias)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAddressMappingAlias = `-- name: UpsertAddressMappingAlias :execrows
INSERT INTO "WhatsAppAddressMapping" (
    "instanceId",
    "alias",
    "normalizedPhone",
    "canonicalJid",
    "lidJid",
    "resolvedAt",
    "expiresAt"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT ("instanceId", "alias") DO UPDATE
SET
    "normalizedPhone" = $3,
    "canonicalJid" = $4,
    "lidJid" = $5,
    "resolvedAt" = $6,
    "expiresAt" = $7,
    "updatedAt" = now()
`

type UpsertAddressMappingAliasParams struct {
	Instanceid      int32            `json:"instanceid"`
	Alias           string           `json:"alias"`
	Normalizedphone string           `json:"normalizedphone"`
	Canonicaljid    string           `json:"canonicaljid"`
	LidJid          pgtype.Text      `json:"lidJid"`
	Resolvedat      pgtype.Timestamp `json:"resolvedat"`
	Expiresat       pgtype.Timestamp `json:"expiresat"`
}

func (q *Queries) UpsertAddressMappingAlias(ctx context.Context, arg UpsertAddressMappingAliasParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertAddressMappingAlias,
		arg.Instanceid,
		arg.Alias,
		arg.Normalizedphone,
		arg.Canonicaljid,
		arg.LidJid,
		arg.Resolvedat,
		arg.Expiresat,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
