// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
)

const createAuth = `-- name: CreateAuth :one
INSERT INTO "Auth" (
    "token",
    "instanceId"
) VALUES (
    $1,
    $2
)
RETURNING id, token, "createdAt", "updatedAt", "instanceId"
`

type CreateAuthParams struct {
	Token      string `json:"token"`
	Instanceid int32  `json:"instanceid"`
}

func (q *Queries) CreateAuth(ctx context.Context, arg CreateAuthParams) (Auth, error) {
	row := q.db.QueryRow(ctx, createAuth, arg.Token, arg.Instanceid)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceId,
	)
	return i, err
}

const findAuthByInstanceID = `-- name: FindAuthByInstanceID :one
SELECT id, token, "createdAt", "updatedAt", "instanceId"
FROM "Auth"
WHERE "instanceId" = $1
`

func (q *Queries) FindAuthByInstanceID(ctx context.Context, instanceid int32) (Auth, error) {
	row := q.db.QueryRow(ctx, findAuthByInstanceID, instanceid)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceId,
	)
	return i, err
}

const lockAuthByInstanceID = `-- name: LockAuthByInstanceID :one
SELECT id, token, "createdAt", "updatedAt", "instanceId"
FROM "Auth"
WHERE "instanceId" = $1
FOR UPDATE
`

func (q *Queries) LockAuthByInstanceID(ctx context.Context, instanceid int32) (Auth, error) {
	row := q.db.QueryRow(ctx, lockAuthByInstanceID, instanceid)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceId,
	)
	return i, err
}

const updateAuthToken = `-- name: UpdateAuthToken :one
UPDATE "Auth"
SET
    "token" = $1,
    "updatedAt" = now()
WHERE "id" = $2
RETURNING id, token, "createdAt", "updatedAt", "instanceId"
`

type UpdateAuthTokenParams struct {
	Token string `json:"token"`
	ID    int32  `json:"id"`
}

func (q *Queries) UpdateAuthToken(ctx context.Context, arg UpdateAuthTokenParams) (Auth, error) {
	row := q.db.QueryRow(ctx, updateAuthToken, arg.Token, arg.ID)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceId,
	)
	return i, err
}

const updateAuthTokenByInstanceAndOldToken = `-- name: UpdateAuthTokenByInstanceAndOldToken :one
UPDATE "Auth"
SET
    "token" = $1,
    "updatedAt" = now()
WHERE "instanceId" = $2
  AND "token" = $3
RETURNING id, token, "createdAt", "updatedAt", "instanceId"
`

type UpdateAuthTokenByInstanceAndOldTokenParams struct {
	Newtoken   string `json:"newtoken"`
	Instanceid int32  `json:"instanceid"`
	Oldtoken   string `json:"oldtoken"`
}

func (q *Queries) UpdateAuthTokenByInstanceAndOldToken(ctx context.Context, arg UpdateAuthTokenByInstanceAndOldTokenParams) (Auth, error) {
	row := q.db.QueryRow(ctx, updateAuthTokenByInstanceAndOldToken, arg.Newtoken, arg.Instanceid, arg.Oldtoken)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceId,
	)
	return i, err
}
