// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package db

import (
	"context"
)

const createChat = `-- name: CreateChat :one
INSERT INTO "Chat" (
    "remoteJid",
    "content",
    "instanceId"
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, "remoteJid", content, "createdAt", "updatedAt", "instanceId"
`

type CreateChatParams struct {
	Remotejid  string `json:"remotejid"`
	Content    []byte `json:"content"`
	Instanceid int32  `json:"instanceid"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat, arg.Remotejid, arg.Content, arg.Instanceid)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.RemoteJid,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceId,
	)
	return i, err
}

const listChats = `-- name: ListChats :many
SELECT id, "remoteJid", content, "createdAt", "updatedAt", "instanceId"
FROM "Chat"
WHERE "instanceId" = $1
  AND (
      $2 = ''
      OR ($2 = 'group' AND right("remoteJid", 5) = '@g.us')
      OR ($2 = 'chats' AND right("remoteJid", 5) <> '@g.us')
  )
ORDER BY "id"
`

type ListChatsParams struct {
	Instanceid int32       `json:"instanceid"`
	Chattype   interface{} `json:"chattype"`
}

func (q *Queries) ListChats(ctx context.Context, arg ListChatsParams) ([]Chat, error) {
	rows, err := q.db.Query(ctx, listChats, arg.Instanceid, arg.Chattype)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.RemoteJid,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstanceId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
