// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContact = `-- name: CreateContact :one
INSERT INTO "Contact" (
    "remoteJid",
    "pushName",
    "profilePicUrl",
    "instanceId"
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, "remoteJid", "pushName", "profilePicUrl", "createdAt", "updatedAt", "instanceId"
`

type CreateContactParams struct {
	Remotejid     string      `json:"remotejid"`
	PushName      pgtype.Text `json:"pushName"`
	ProfilePicUrl pgtype.Text `json:"profilePicUrl"`
	Instanceid    int32       `json:"instanceid"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.Remotejid,
		arg.PushName,
		arg.ProfilePicUrl,
		arg.Instanceid,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.RemoteJid,
		&i.PushName,
		&i.ProfilePicUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceId,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many
SELECT id, "remoteJid", "pushName", "profilePicUrl", "createdAt", "updatedAt", "instanceId"
FROM "Contact"
WHERE "instanceId" = $1
  AND (
      ($2::boolean AND "id" = $3)
      OR (
          NOT $2::boolean
          AND (NOT $4::boolean OR "remoteJid" = $5)
          AND (NOT $6::boolean OR "pushName" = $7)
      )
  )
ORDER BY "id"
`

type ListContactsParams struct {
	Instanceid      int32       `json:"instanceid"`
	Filterid        bool        `json:"filterid"`
	ID              int32       `json:"id"`
	Filterremotejid bool        `json:"filterremotejid"`
	Remotejid       string      `json:"remotejid"`
	Filterpushname  bool        `json:"filterpushname"`
	Pushname        pgtype.Text `json:"pushname"`
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts,
		arg.Instanceid,
		arg.Filterid,
		arg.ID,
		arg.Filterremotejid,
		arg.Remotejid,
		arg.Filterpushname,
		arg.Pushname,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.RemoteJid,
			&i.PushName,
			&i.ProfilePicUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstanceId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContact = `-- name: UpsertContact :one
INSERT INTO "Contact" (
    "remoteJid",
    "pushName",
    "profilePicUrl",
    "instanceId"
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT ("instanceId", "remoteJid")
DO UPDATE SET
    "pushName" = COALESCE(NULLIF(EXCLUDED."pushName", ''), "Contact"."pushName"),
    "profilePicUrl" = COALESCE(NULLIF(EXCLUDED."profilePicUrl", ''), "Contact"."profilePicUrl"),
    "updatedAt" = now()
RETURNING id, "remoteJid", "pushName", "profilePicUrl", "createdAt", "updatedAt", "instanceId"
`

type UpsertContactParams struct {
	Remotejid     string      `json:"remotejid"`
	PushName      pgtype.Text `json:"pushName"`
	ProfilePicUrl pgtype.Text `json:"profilePicUrl"`
	Instanceid    int32       `json:"instanceid"`
}

func (q *Queries) UpsertContact(ctx context.Context, arg UpsertContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, upsertContact,
		arg.Remotejid,
		arg.PushName,
		arg.ProfilePicUrl,
		arg.Instanceid,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.RemoteJid,
		&i.PushName,
		&i.ProfilePicUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceId,
	)
	return i, err
}
