// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearWhatsAppDevice = `-- name: ClearWhatsAppDevice :execrows
WITH update_instance AS (
    UPDATE "Instance"
    SET
        "ownerJid" = NULL,
        "updatedAt" = now()
    WHERE "id" = $1
)
UPDATE "InstanceWhatsAppConnection"
SET
    "whatsappDeviceJid" = NULL,
    "whatsappOwnerJid" = NULL,
    "whatsappPhoneNumber" = NULL,
    "updatedAt" = now()
WHERE "instanceId" = $1
`

func (q *Queries) ClearWhatsAppDevice(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, clearWhatsAppDevice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countInstanceDependencies = `-- name: CountInstanceDependencies :one
SELECT
    (SELECT count(*) FROM "Message" m WHERE m."instanceId" = $1) AS "messages",
    (SELECT count(*) FROM "Chat" c WHERE c."instanceId" = $1) AS "chats",
    (SELECT count(*) FROM "Contact" ct WHERE ct."instanceId" = $1) AS "contacts",
    (SELECT count(*) FROM "Webhook" w WHERE w."instanceId" = $1) AS "webhooks"
`

type CountInstanceDependenciesRow struct {
	Messages int64 `json:"messages"`
	Chats    int64 `json:"chats"`
	Contacts int64 `json:"contacts"`
	Webhooks int64 `json:"webhooks"`
}

func (q *Queries) CountInstanceDependencies(ctx context.Context, instanceid int32) (CountInstanceDependenciesRow, error) {
	row := q.db.QueryRow(ctx, countInstanceDependencies, instanceid)
	var i CountInstanceDependenciesRow
	err := row.Scan(
		&i.Messages,
		&i.Chats,
		&i.Contacts,
		&i.Webhooks,
	)
	return i, err
}

const createInstance = `-- name: CreateInstance :one
INSERT INTO "Instance" (
    "name",
    "description",
    "connectionStatus",
    "ownerJid",
    "profilePicUrl",
    "externalAttributes"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, name, description, "connectionStatus", "ownerJid", "profilePicUrl", "createdAt", "updatedAt", "externalAttributes"
`

type CreateInstanceParams struct {
	Name               string         `json:"name"`
	Description        pgtype.Text    `json:"description"`
	Connectionstatus   InstanceStatus `json:"connectionstatus"`
	OwnerJid           pgtype.Text    `json:"ownerJid"`
	ProfilePicUrl      pgtype.Text    `json:"profilePicUrl"`
	ExternalAttributes []byte         `json:"externalAttributes"`
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, createInstance,
		arg.Name,
		arg.Description,
		arg.Connectionstatus,
		arg.OwnerJid,
		arg.ProfilePicUrl,
		arg.ExternalAttributes,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ConnectionStatus,
		&i.OwnerJid,
		&i.ProfilePicUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalAttributes,
	)
	return i, err
}

const deleteInstance = `-- name: DeleteInstance :execrows
DELETE FROM "Instance"
WHERE "id" = $1
`

func (q *Queries) DeleteInstance(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInstance, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAutoConnectInstances = `-- name: FindAutoConnectInstances :many
SELECT
    i."id",
    i."name",
    i."description",
    i."connectionStatus",
    i."ownerJid",
    i."profilePicUrl",
    i."createdAt",
    i."updatedAt",
    i."externalAttributes",
    c."connectionStatus" AS "whatsappConnectionStatus",
    c."whatsappDeviceJid" AS "whatsappDeviceJid",
    c."whatsappOwnerJid" AS "whatsappOwnerJid",
    c."whatsappPhoneNumber" AS "whatsappPhoneNumber",
    c."profilePicId" AS "profilePicId",
    c."lastConnectedAt" AS "lastConnectedAt",
    c."lastDisconnectedAt" AS "lastDisconnectedAt",
    c."lastConnectionAttemptAt" AS "lastConnectionAttemptAt",
    c."lastConnectionError" AS "lastConnectionError",
    c."lastConnectionEvent" AS "lastConnectionEvent",
    c."connectionAttempts" AS "connectionAttempts"
FROM "Instance" i
JOIN "InstanceWhatsAppConnection" c ON c."instanceId" = i."id"
WHERE c."connectionStatus" IN (
    'online',
    'connecting',
    'reconnecting',
    'connection_timeout',
    'connection_error',
    'keepalive_timeout'
)
  AND i."connectionStatus" = 'ONLINE'
  AND c."whatsappDeviceJid" IS NOT NULL
ORDER BY i."id"
`

type FindAutoConnectInstancesRow struct {
	ID                       int32            `json:"id"`
	Name                     string           `json:"name"`
	Description              pgtype.Text      `json:"description"`
	ConnectionStatus         InstanceStatus   `json:"connectionStatus"`
	OwnerJid                 pgtype.Text      `json:"ownerJid"`
	ProfilePicUrl            pgtype.Text      `json:"profilePicUrl"`
	CreatedAt                pgtype.Timestamp `json:"createdAt"`
	UpdatedAt                pgtype.Timestamp `json:"updatedAt"`
	ExternalAttributes       []byte           `json:"externalAttributes"`
	WhatsappConnectionStatus string           `json:"whatsappConnectionStatus"`
	WhatsappDeviceJid        pgtype.Text      `json:"whatsappDeviceJid"`
	WhatsappOwnerJid         pgtype.Text      `json:"whatsappOwnerJid"`
	WhatsappPhoneNumber      pgtype.Text      `json:"whatsappPhoneNumber"`
	ProfilePicId             pgtype.Text      `json:"profilePicId"`
	LastConnectedAt          pgtype.Timestamp `json:"lastConnectedAt"`
	LastDisconnectedAt       pgtype.Timestamp `json:"lastDisconnectedAt"`
	LastConnectionAttemptAt  pgtype.Timestamp `json:"lastConnectionAttemptAt"`
	LastConnectionError      pgtype.Text      `json:"lastConnectionError"`
	LastConnectionEvent      pgtype.Text      `json:"lastConnectionEvent"`
	ConnectionAttempts       int32            `json:"connectionAttempts"`
}

func (q *Queries) FindAutoConnectInstances(ctx context.Context) ([]FindAutoConnectInstancesRow, error) {
	rows, err := q.db.Query(ctx, findAutoConnectInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAutoConnectInstancesRow
	for rows.Next() {
		var i FindAutoConnectInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ConnectionStatus,
			&i.OwnerJid,
			&i.ProfilePicUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalAttributes,
			&i.WhatsappConnectionStatus,
			&i.WhatsappDeviceJid,
			&i.WhatsappOwnerJid,
			&i.WhatsappPhoneNumber,
			&i.ProfilePicId,
			&i.LastConnectedAt,
			&i.LastDisconnectedAt,
			&i.LastConnectionAttemptAt,
			&i.LastConnectionError,
			&i.LastConnectionEvent,
			&i.ConnectionAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findInstanceDetailsByName = `-- name: FindInstanceDetailsByName :one
SELECT
    i."id",
    i."name",
    i."description",
    i."connectionStatus",
    i."ownerJid",
    i."profilePicUrl",
    i."createdAt",
    i."updatedAt",
    i."externalAttributes",
    c."connectionStatus" AS "whatsappConnectionStatus",
    c."whatsappDeviceJid" AS "whatsappDeviceJid",
    c."whatsappOwnerJid" AS "whatsappOwnerJid",
    c."whatsappPhoneNumber" AS "whatsappPhoneNumber",
    c."profilePicId" AS "profilePicId",
    c."lastConnectedAt" AS "lastConnectedAt",
    c."lastDisconnectedAt" AS "lastDisconnectedAt",
    c."lastConnectionAttemptAt" AS "lastConnectionAttemptAt",
    c."lastConnectionError" AS "lastConnectionError",
    c."lastConnectionEvent" AS "lastConnectionEvent",
    c."connectionAttempts" AS "connectionAttempts",
    w."id" AS "webhookId",
    w."enabled" AS "webhookEnabled",
    w."url" AS "webhookUrl",
    w."events" AS "webhookEvents",
    w."createdAt" AS "webhookCreatedAt",
    w."updatedAt" AS "webhookUpdatedAt",
    w."instanceId" AS "webhookInstanceId"
FROM "Instance" i
LEFT JOIN "InstanceWhatsAppConnection" c ON c."instanceId" = i."id"
LEFT JOIN "Webhook" w ON w."instanceId" = i."id"
WHERE i."name" = $1
`

type FindInstanceDetailsByNameRow struct {
	ID                       int32            `json:"id"`
	Name                     string           `json:"name"`
	Description              pgtype.Text      `json:"description"`
	ConnectionStatus         InstanceStatus   `json:"connectionStatus"`
	OwnerJid                 pgtype.Text      `json:"ownerJid"`
	ProfilePicUrl            pgtype.Text      `json:"profilePicUrl"`
	CreatedAt                pgtype.Timestamp `json:"createdAt"`
	UpdatedAt                pgtype.Timestamp `json:"updatedAt"`
	ExternalAttributes       []byte           `json:"externalAttributes"`
	WhatsappConnectionStatus pgtype.Text      `json:"whatsappConnectionStatus"`
	WhatsappDeviceJid        pgtype.Text      `json:"whatsappDeviceJid"`
	WhatsappOwnerJid         pgtype.Text      `json:"whatsappOwnerJid"`
	WhatsappPhoneNumber      pgtype.Text      `json:"whatsappPhoneNumber"`
	ProfilePicId             pgtype.Text      `json:"profilePicId"`
	LastConnectedAt          pgtype.Timestamp `json:"lastConnectedAt"`
	LastDisconnectedAt       pgtype.Timestamp `json:"lastDisconnectedAt"`
	LastConnectionAttemptAt  pgtype.Timestamp `json:"lastConnectionAttemptAt"`
	LastConnectionError      pgtype.Text      `json:"lastConnectionError"`
	LastConnectionEvent      pgtype.Text      `json:"lastConnectionEvent"`
	ConnectionAttempts       pgtype.Int4      `json:"connectionAttempts"`
	WebhookId                pgtype.Int4      `json:"webhookId"`
	WebhookEnabled           pgtype.Bool      `json:"webhookEnabled"`
	WebhookUrl               pgtype.Text      `json:"webhookUrl"`
	WebhookEvents            []byte           `json:"webhookEvents"`
	WebhookCreatedAt         pgtype.Timestamp `json:"webhookCreatedAt"`
	WebhookUpdatedAt         pgtype.Timestamp `json:"webhookUpdatedAt"`
	WebhookInstanceId        pgtype.Int4      `json:"webhookInstanceId"`
}

func (q *Queries) FindInstanceDetailsByName(ctx context.Context, name string) (FindInstanceDetailsByNameRow, error) {
	row := q.db.QueryRow(ctx, findInstanceDetailsByName, name)
	var i FindInstanceDetailsByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ConnectionStatus,
		&i.OwnerJid,
		&i.ProfilePicUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalAttributes,
		&i.WhatsappConnectionStatus,
		&i.WhatsappDeviceJid,
		&i.WhatsappOwnerJid,
		&i.WhatsappPhoneNumber,
		&i.ProfilePicId,
		&i.LastConnectedAt,
		&i.LastDisconnectedAt,
		&i.LastConnectionAttemptAt,
		&i.LastConnectionError,
		&i.LastConnectionEvent,
		&i.ConnectionAttempts,
		&i.WebhookId,
		&i.WebhookEnabled,
		&i.WebhookUrl,
		&i.WebhookEvents,
		&i.WebhookCreatedAt,
		&i.WebhookUpdatedAt,
		&i.WebhookInstanceId,
	)
	return i, err
}

const findInstanceWithAuthByName = `-- name: FindInstanceWithAuthByName :one
SELECT
    i."id",
    i."name",
    i."description",
    i."connectionStatus",
    i."ownerJid",
    i."profilePicUrl",
    i."createdAt",
    i."updatedAt",
    i."externalAttributes",
    c."connectionStatus" AS "whatsappConnectionStatus",
    c."whatsappDeviceJid" AS "whatsappDeviceJid",
    c."whatsappOwnerJid" AS "whatsappOwnerJid",
    c."whatsappPhoneNumber" AS "whatsappPhoneNumber",
    c."profilePicId" AS "profilePicId",
    c."lastConnectedAt" AS "lastConnectedAt",
    c."lastDisconnectedAt" AS "lastDisconnectedAt",
    c."lastConnectionAttemptAt" AS "lastConnectionAttemptAt",
    c."lastConnectionError" AS "lastConnectionError",
    c."lastConnectionEvent" AS "lastConnectionEvent",
    c."connectionAttempts" AS "connectionAttempts",
    a."id" AS "authId",
    a."token" AS "authToken",
    a."createdAt" AS "authCreatedAt",
    a."updatedAt" AS "authUpdatedAt",
    a."instanceId" AS "authInstanceId"
FROM "Instance" i
LEFT JOIN "InstanceWhatsAppConnection" c ON c."instanceId" = i."id"
LEFT JOIN "Auth" a ON a."instanceId" = i."id"
WHERE i."name" = $1
`

type FindInstanceWithAuthByNameRow struct {
	ID                       int32            `json:"id"`
	Name                     string           `json:"name"`
	Description              pgtype.Text      `json:"description"`
	ConnectionStatus         InstanceStatus   `json:"connectionStatus"`
	OwnerJid                 pgtype.Text      `json:"ownerJid"`
	ProfilePicUrl            pgtype.Text      `json:"profilePicUrl"`
	CreatedAt                pgtype.Timestamp `json:"createdAt"`
	UpdatedAt                pgtype.Timestamp `json:"updatedAt"`
	ExternalAttributes       []byte           `json:"externalAttributes"`
	WhatsappConnectionStatus pgtype.Text      `json:"whatsappConnectionStatus"`
	WhatsappDeviceJid        pgtype.Text      `json:"whatsappDeviceJid"`
	WhatsappOwnerJid         pgtype.Text      `json:"whatsappOwnerJid"`
	WhatsappPhoneNumber      pgtype.Text      `json:"whatsappPhoneNumber"`
	ProfilePicId             pgtype.Text      `json:"profilePicId"`
	LastConnectedAt          pgtype.Timestamp `json:"lastConnectedAt"`
	LastDisconnectedAt       pgtype.Timestamp `json:"lastDisconnectedAt"`
	LastConnectionAttemptAt  pgtype.Timestamp `json:"lastConnectionAttemptAt"`
	LastConnectionError      pgtype.Text      `json:"lastConnectionError"`
	LastConnectionEvent      pgtype.Text      `json:"lastConnectionEvent"`
	ConnectionAttempts       pgtype.Int4      `json:"connectionAttempts"`
	AuthId                   pgtype.Int4      `json:"authId"`
	AuthToken                pgtype.Text      `json:"authToken"`
	AuthCreatedAt            pgtype.Timestamp `json:"authCreatedAt"`
	AuthUpdatedAt            pgtype.Timestamp `json:"authUpdatedAt"`
	AuthInstanceId           pgtype.Int4      `json:"authInstanceId"`
}

func (q *Queries) FindInstanceWithAuthByName(ctx context.Context, name string) (FindInstanceWithAuthByNameRow, error) {
	row := q.db.QueryRow(ctx, findInstanceWithAuthByName, name)
	var i FindInstanceWithAuthByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ConnectionStatus,
		&i.OwnerJid,
		&i.ProfilePicUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalAttributes,
		&i.WhatsappConnectionStatus,
		&i.WhatsappDeviceJid,
		&i.WhatsappOwnerJid,
		&i.WhatsappPhoneNumber,
		&i.ProfilePicId,
		&i.LastConnectedAt,
		&i.LastDisconnectedAt,
		&i.LastConnectionAttemptAt,
		&i.LastConnectionError,
		&i.LastConnectionEvent,
		&i.ConnectionAttempts,
		&i.AuthId,
		&i.AuthToken,
		&i.AuthCreatedAt,
		&i.AuthUpdatedAt,
		&i.AuthInstanceId,
	)
	return i, err
}

const findInstanceWithAuthByID = `-- name: FindInstanceWithAuthByID :one
SELECT
    i."id",
    i."name",
    i."description",
    i."connectionStatus",
    i."ownerJid",
    i."profilePicUrl",
    i."createdAt",
    i."updatedAt",
    i."externalAttributes",
    c."connectionStatus" AS "whatsappConnectionStatus",
    c."whatsappDeviceJid" AS "whatsappDeviceJid",
    c."whatsappOwnerJid" AS "whatsappOwnerJid",
    c."whatsappPhoneNumber" AS "whatsappPhoneNumber",
    c."profilePicId" AS "profilePicId",
    c."lastConnectedAt" AS "lastConnectedAt",
    c."lastDisconnectedAt" AS "lastDisconnectedAt",
    c."lastConnectionAttemptAt" AS "lastConnectionAttemptAt",
    c."lastConnectionError" AS "lastConnectionError",
    c."lastConnectionEvent" AS "lastConnectionEvent",
    c."connectionAttempts" AS "connectionAttempts",
    a."id" AS "authId",
    a."token" AS "authToken",
    a."createdAt" AS "authCreatedAt",
    a."updatedAt" AS "authUpdatedAt",
    a."instanceId" AS "authInstanceId"
FROM "Instance" i
LEFT JOIN "InstanceWhatsAppConnection" c ON c."instanceId" = i."id"
LEFT JOIN "Auth" a ON a."instanceId" = i."id"
WHERE i."id" = $1
`

type FindInstanceWithAuthByIDRow = FindInstanceWithAuthByNameRow

func (q *Queries) FindInstanceWithAuthByID(ctx context.Context, id int32) (FindInstanceWithAuthByIDRow, error) {
	row := q.db.QueryRow(ctx, findInstanceWithAuthByID, id)
	var i FindInstanceWithAuthByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ConnectionStatus,
		&i.OwnerJid,
		&i.ProfilePicUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalAttributes,
		&i.WhatsappConnectionStatus,
		&i.WhatsappDeviceJid,
		&i.WhatsappOwnerJid,
		&i.WhatsappPhoneNumber,
		&i.ProfilePicId,
		&i.LastConnectedAt,
		&i.LastDisconnectedAt,
		&i.LastConnectionAttemptAt,
		&i.LastConnectionError,
		&i.LastConnectionEvent,
		&i.ConnectionAttempts,
		&i.AuthId,
		&i.AuthToken,
		&i.AuthCreatedAt,
		&i.AuthUpdatedAt,
		&i.AuthInstanceId,
	)
	return i, err
}

const instanceExists = `-- name: InstanceExists :one
SELECT EXISTS (
    SELECT 1
    FROM "Instance"
    WHERE "id" = $1
) AS "exists"
`

func (q *Queries) InstanceExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, instanceExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listInstanceDetails = `-- name: ListInstanceDetails :many
SELECT
    i."id",
    i."name",
    i."description",
    i."connectionStatus",
    i."ownerJid",
    i."profilePicUrl",
    i."createdAt",
    i."updatedAt",
    i."externalAttributes",
    c."connectionStatus" AS "whatsappConnectionStatus",
    c."whatsappDeviceJid" AS "whatsappDeviceJid",
    c."whatsappOwnerJid" AS "whatsappOwnerJid",
    c."whatsappPhoneNumber" AS "whatsappPhoneNumber",
    c."profilePicId" AS "profilePicId",
    c."lastConnectedAt" AS "lastConnectedAt",
    c."lastDisconnectedAt" AS "lastDisconnectedAt",
    c."lastConnectionAttemptAt" AS "lastConnectionAttemptAt",
    c."lastConnectionError" AS "lastConnectionError",
    c."lastConnectionEvent" AS "lastConnectionEvent",
    c."connectionAttempts" AS "connectionAttempts",
    a."id" AS "authId",
    a."token" AS "authToken",
    a."createdAt" AS "authCreatedAt",
    a."updatedAt" AS "authUpdatedAt",
    a."instanceId" AS "authInstanceId",
    w."id" AS "webhookId",
    w."enabled" AS "webhookEnabled",
    w."url" AS "webhookUrl",
    w."events" AS "webhookEvents",
    w."createdAt" AS "webhookCreatedAt",
    w."updatedAt" AS "webhookUpdatedAt",
    w."instanceId" AS "webhookInstanceId"
FROM "Instance" i
LEFT JOIN "InstanceWhatsAppConnection" c ON c."instanceId" = i."id"
LEFT JOIN "Auth" a ON a."instanceId" = i."id"
LEFT JOIN "Webhook" w ON w."instanceId" = i."id"
WHERE
    $1::boolean = false
    OR i."name" ILIKE '%' || $2 || '%'
ORDER BY i."createdAt" DESC
`

type ListInstanceDetailsParams struct {
	FilterByName bool        `json:"filterByName"`
	Name         pgtype.Text `json:"name"`
}

type ListInstanceDetailsRow struct {
	ID                       int32            `json:"id"`
	Name                     string           `json:"name"`
	Description              pgtype.Text      `json:"description"`
	ConnectionStatus         InstanceStatus   `json:"connectionStatus"`
	OwnerJid                 pgtype.Text      `json:"ownerJid"`
	ProfilePicUrl            pgtype.Text      `json:"profilePicUrl"`
	CreatedAt                pgtype.Timestamp `json:"createdAt"`
	UpdatedAt                pgtype.Timestamp `json:"updatedAt"`
	ExternalAttributes       []byte           `json:"externalAttributes"`
	WhatsappConnectionStatus pgtype.Text      `json:"whatsappConnectionStatus"`
	WhatsappDeviceJid        pgtype.Text      `json:"whatsappDeviceJid"`
	WhatsappOwnerJid         pgtype.Text      `json:"whatsappOwnerJid"`
	WhatsappPhoneNumber      pgtype.Text      `json:"whatsappPhoneNumber"`
	ProfilePicId             pgtype.Text      `json:"profilePicId"`
	LastConnectedAt          pgtype.Timestamp `json:"lastConnectedAt"`
	LastDisconnectedAt       pgtype.Timestamp `json:"lastDisconnectedAt"`
	LastConnectionAttemptAt  pgtype.Timestamp `json:"lastConnectionAttemptAt"`
	LastConnectionError      pgtype.Text      `json:"lastConnectionError"`
	LastConnectionEvent      pgtype.Text      `json:"lastConnectionEvent"`
	ConnectionAttempts       pgtype.Int4      `json:"connectionAttempts"`
	AuthId                   pgtype.Int4      `json:"authId"`
	AuthToken                pgtype.Text      `json:"authToken"`
	AuthCreatedAt            pgtype.Timestamp `json:"authCreatedAt"`
	AuthUpdatedAt            pgtype.Timestamp `json:"authUpdatedAt"`
	AuthInstanceId           pgtype.Int4      `json:"authInstanceId"`
	WebhookId                pgtype.Int4      `json:"webhookId"`
	WebhookEnabled           pgtype.Bool      `json:"webhookEnabled"`
	WebhookUrl               pgtype.Text      `json:"webhookUrl"`
	WebhookEvents            []byte           `json:"webhookEvents"`
	WebhookCreatedAt         pgtype.Timestamp `json:"webhookCreatedAt"`
	WebhookUpdatedAt         pgtype.Timestamp `json:"webhookUpdatedAt"`
	WebhookInstanceId        pgtype.Int4      `json:"webhookInstanceId"`
}

func (q *Queries) ListInstanceDetails(ctx context.Context, arg ListInstanceDetailsParams) ([]ListInstanceDetailsRow, error) {
	rows, err := q.db.Query(ctx, listInstanceDetails, arg.FilterByName, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInstanceDetailsRow
	for rows.Next() {
		var i ListInstanceDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ConnectionStatus,
			&i.OwnerJid,
			&i.ProfilePicUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalAttributes,
			&i.WhatsappConnectionStatus,
			&i.WhatsappDeviceJid,
			&i.WhatsappOwnerJid,
			&i.WhatsappPhoneNumber,
			&i.ProfilePicId,
			&i.LastConnectedAt,
			&i.LastDisconnectedAt,
			&i.LastConnectionAttemptAt,
			&i.LastConnectionError,
			&i.LastConnectionEvent,
			&i.ConnectionAttempts,
			&i.AuthId,
			&i.AuthToken,
			&i.AuthCreatedAt,
			&i.AuthUpdatedAt,
			&i.AuthInstanceId,
			&i.WebhookId,
			&i.WebhookEnabled,
			&i.WebhookUrl,
			&i.WebhookEvents,
			&i.WebhookCreatedAt,
			&i.WebhookUpdatedAt,
			&i.WebhookInstanceId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstancesWithAuth = `-- name: ListInstancesWithAuth :many
SELECT
    i."id",
    i."name",
    i."description",
    i."connectionStatus",
    i."ownerJid",
    i."profilePicUrl",
    i."createdAt",
    i."updatedAt",
    i."externalAttributes",
    c."connectionStatus" AS "whatsappConnectionStatus",
    c."whatsappDeviceJid" AS "whatsappDeviceJid",
    c."whatsappOwnerJid" AS "whatsappOwnerJid",
    c."whatsappPhoneNumber" AS "whatsappPhoneNumber",
    c."profilePicId" AS "profilePicId",
    c."lastConnectedAt" AS "lastConnectedAt",
    c."lastDisconnectedAt" AS "lastDisconnectedAt",
    c."lastConnectionAttemptAt" AS "lastConnectionAttemptAt",
    c."lastConnectionError" AS "lastConnectionError",
    c."lastConnectionEvent" AS "lastConnectionEvent",
    c."connectionAttempts" AS "connectionAttempts",
    a."id" AS "authId",
    a."token" AS "authToken",
    a."createdAt" AS "authCreatedAt",
    a."updatedAt" AS "authUpdatedAt",
    a."instanceId" AS "authInstanceId"
FROM "Instance" i
LEFT JOIN "InstanceWhatsAppConnection" c ON c."instanceId" = i."id"
LEFT JOIN "Auth" a ON a."instanceId" = i."id"
ORDER BY i."id"
`

type ListInstancesWithAuthRow struct {
	ID                       int32            `json:"id"`
	Name                     string           `json:"name"`
	Description              pgtype.Text      `json:"description"`
	ConnectionStatus         InstanceStatus   `json:"connectionStatus"`
	OwnerJid                 pgtype.Text      `json:"ownerJid"`
	ProfilePicUrl            pgtype.Text      `json:"profilePicUrl"`
	CreatedAt                pgtype.Timestamp `json:"createdAt"`
	UpdatedAt                pgtype.Timestamp `json:"updatedAt"`
	ExternalAttributes       []byte           `json:"externalAttributes"`
	WhatsappConnectionStatus pgtype.Text      `json:"whatsappConnectionStatus"`
	WhatsappDeviceJid        pgtype.Text      `json:"whatsappDeviceJid"`
	WhatsappOwnerJid         pgtype.Text      `json:"whatsappOwnerJid"`
	WhatsappPhoneNumber      pgtype.Text      `json:"whatsappPhoneNumber"`
	ProfilePicId             pgtype.Text      `json:"profilePicId"`
	LastConnectedAt          pgtype.Timestamp `json:"lastConnectedAt"`
	LastDisconnectedAt       pgtype.Timestamp `json:"lastDisconnectedAt"`
	LastConnectionAttemptAt  pgtype.Timestamp `json:"lastConnectionAttemptAt"`
	LastConnectionError      pgtype.Text      `json:"lastConnectionError"`
	LastConnectionEvent      pgtype.Text      `json:"lastConnectionEvent"`
	ConnectionAttempts       pgtype.Int4      `json:"connectionAttempts"`
	AuthId                   pgtype.Int4      `json:"authId"`
	AuthToken                pgtype.Text      `json:"authToken"`
	AuthCreatedAt            pgtype.Timestamp `json:"authCreatedAt"`
	AuthUpdatedAt            pgtype.Timestamp `json:"authUpdatedAt"`
	AuthInstanceId           pgtype.Int4      `json:"authInstanceId"`
}

func (q *Queries) ListInstancesWithAuth(ctx context.Context) ([]ListInstancesWithAuthRow, error) {
	rows, err := q.db.Query(ctx, listInstancesWithAuth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInstancesWithAuthRow
	for rows.Next() {
		var i ListInstancesWithAuthRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ConnectionStatus,
			&i.OwnerJid,
			&i.ProfilePicUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalAttributes,
			&i.WhatsappConnectionStatus,
			&i.WhatsappDeviceJid,
			&i.WhatsappOwnerJid,
			&i.WhatsappPhoneNumber,
			&i.ProfilePicId,
			&i.LastConnectedAt,
			&i.LastDisconnectedAt,
			&i.LastConnectionAttemptAt,
			&i.LastConnectionError,
			&i.LastConnectionEvent,
			&i.ConnectionAttempts,
			&i.AuthId,
			&i.AuthToken,
			&i.AuthCreatedAt,
			&i.AuthUpdatedAt,
			&i.AuthInstanceId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInstanceByID = `-- name: LockInstanceByID :one
SELECT "id"
FROM "Instance"
WHERE "id" = $1
FOR UPDATE
`

func (q *Queries) LockInstanceByID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, lockInstanceByID, id)
	err := row.Scan(&id)
	return id, err
}

const releaseInstanceConnectionLock = `-- name: ReleaseInstanceConnectionLock :one
SELECT pg_advisory_unlock(hashtext($1))
`

func (q *Queries) ReleaseInstanceConnectionLock(ctx context.Context, instanceid string) (bool, error) {
	row := q.db.QueryRow(ctx, releaseInstanceConnectionLock, instanceid)
	var pg_advisory_unlock bool
	err := row.Scan(&pg_advisory_unlock)
	return pg_advisory_unlock, err
}

const saveWhatsAppDevice = `-- name: SaveWhatsAppDevice :execrows
WITH update_instance AS (
    UPDATE "Instance"
    SET
        "ownerJid" = $3,
        "updatedAt" = now()
    WHERE "id" = $1
)
INSERT INTO "InstanceWhatsAppConnection" (
    "instanceId",
    "whatsappDeviceJid",
    "whatsappOwnerJid",
    "whatsappPhoneNumber"
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT ("instanceId") DO UPDATE
SET
    "whatsappDeviceJid" = $2,
    "whatsappOwnerJid" = $3,
    "whatsappPhoneNumber" = $4,
    "updatedAt" = now()
`

type SaveWhatsAppDeviceParams struct {
	ID                  int32       `json:"id"`
	Whatsappdevicejid   pgtype.Text `json:"whatsappdevicejid"`
	Whatsappownerjid    pgtype.Text `json:"whatsappownerjid"`
	Whatsappphonenumber pgtype.Text `json:"whatsappphonenumber"`
}

func (q *Queries) SaveWhatsAppDevice(ctx context.Context, arg SaveWhatsAppDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveWhatsAppDevice,
		arg.ID,
		arg.Whatsappdevicejid,
		arg.Whatsappownerjid,
		arg.Whatsappphonenumber,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tryAcquireInstanceConnectionLock = `-- name: TryAcquireInstanceConnectionLock :one
SELECT pg_try_advisory_lock(hashtext($1))
`

func (q *Queries) TryAcquireInstanceConnectionLock(ctx context.Context, instanceid string) (bool, error) {
	row := q.db.QueryRow(ctx, tryAcquireInstanceConnectionLock, instanceid)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}

const updateInstance = `-- name: UpdateInstance :one
UPDATE "Instance"
SET
    "name" = CASE WHEN $1::boolean THEN $2 ELSE "name" END,
    "description" = CASE WHEN $3::boolean THEN $4 ELSE "description" END,
    "profilePicUrl" = CASE WHEN $5::boolean THEN $6 ELSE "profilePicUrl" END,
    "externalAttributes" = CASE WHEN $7::boolean THEN $8 ELSE "externalAttributes" END,
    "updatedAt" = now()
WHERE "id" = $9
RETURNING id, name, description, "connectionStatus", "ownerJid", "profilePicUrl", "createdAt", "updatedAt", "externalAttributes"
`

type UpdateInstanceParams struct {
	Setname               bool        `json:"setname"`
	Name                  string      `json:"name"`
	Setdescription        bool        `json:"setdescription"`
	Description           pgtype.Text `json:"description"`
	Setprofilepicurl      bool        `json:"setprofilepicurl"`
	ProfilePicUrl         pgtype.Text `json:"profilePicUrl"`
	Setexternalattributes bool        `json:"setexternalattributes"`
	ExternalAttributes    []byte      `json:"externalAttributes"`
	ID                    int32       `json:"id"`
}

func (q *Queries) UpdateInstance(ctx context.Context, arg UpdateInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, updateInstance,
		arg.Setname,
		arg.Name,
		arg.Setdescription,
		arg.Description,
		arg.Setprofilepicurl,
		arg.ProfilePicUrl,
		arg.Setexternalattributes,
		arg.ExternalAttributes,
		arg.ID,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ConnectionStatus,
		&i.OwnerJid,
		&i.ProfilePicUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalAttributes,
	)
	return i, err
}

const updateInstanceConnectionState = `-- name: UpdateInstanceConnectionState :execrows
INSERT INTO "InstanceWhatsAppConnection" (
    "instanceId",
    "connectionStatus",
    "lastConnectedAt",
    "lastDisconnectedAt",
    "lastConnectionAttemptAt",
    "lastConnectionError",
    "lastConnectionEvent",
    "connectionAttempts"
) VALUES (
    $1,
    CASE WHEN $2::boolean THEN $3::text ELSE 'offline' END,
    $4,
    $5,
    $6,
    $7,
    $8,
    CASE WHEN $9::boolean THEN 1 ELSE 0 END
)
ON CONFLICT ("instanceId") DO UPDATE
SET
    "connectionStatus" = CASE WHEN $2::boolean THEN $3::text ELSE "InstanceWhatsAppConnection"."connectionStatus" END,
    "lastConnectedAt" = CASE WHEN $10::boolean THEN $4 ELSE "InstanceWhatsAppConnection"."lastConnectedAt" END,
    "lastDisconnectedAt" = CASE WHEN $11::boolean THEN $5 ELSE "InstanceWhatsAppConnection"."lastDisconnectedAt" END,
    "lastConnectionAttemptAt" = CASE WHEN $12::boolean THEN $6 ELSE "InstanceWhatsAppConnection"."lastConnectionAttemptAt" END,
    "lastConnectionError" = CASE WHEN $13::boolean THEN $7 ELSE "InstanceWhatsAppConnection"."lastConnectionError" END,
    "lastConnectionEvent" = CASE WHEN $14::boolean THEN $8 ELSE "InstanceWhatsAppConnection"."lastConnectionEvent" END,
    "connectionAttempts" = CASE
        WHEN $15::boolean THEN 0
        WHEN $9::boolean THEN "InstanceWhatsAppConnection"."connectionAttempts" + 1
        ELSE "InstanceWhatsAppConnection"."connectionAttempts"
    END,
    "updatedAt" = now()
`

type UpdateInstanceConnectionStateParams struct {
	ID                         int32            `json:"id"`
	Setconnectionstatus        bool             `json:"setconnectionstatus"`
	Connectionstatus           string           `json:"connectionstatus"`
	LastConnectedAt            pgtype.Timestamp `json:"lastConnectedAt"`
	LastDisconnectedAt         pgtype.Timestamp `json:"lastDisconnectedAt"`
	LastConnectionAttemptAt    pgtype.Timestamp `json:"lastConnectionAttemptAt"`
	LastConnectionError        pgtype.Text      `json:"lastConnectionError"`
	LastConnectionEvent        pgtype.Text      `json:"lastConnectionEvent"`
	Incrementattempts          bool             `json:"incrementattempts"`
	Setlastconnectedat         bool             `json:"setlastconnectedat"`
	Setlastdisconnectedat      bool             `json:"setlastdisconnectedat"`
	Setlastconnectionattemptat bool             `json:"setlastconnectionattemptat"`
	Setlastconnectionerror     bool             `json:"setlastconnectionerror"`
	Setlastconnectionevent     bool             `json:"setlastconnectionevent"`
	Resetattempts              bool             `json:"resetattempts"`
}

func (q *Queries) UpdateInstanceConnectionState(ctx context.Context, arg UpdateInstanceConnectionStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateInstanceConnectionState,
		arg.ID,
		arg.Setconnectionstatus,
		arg.Connectionstatus,
		arg.LastConnectedAt,
		arg.LastDisconnectedAt,
		arg.LastConnectionAttemptAt,
		arg.LastConnectionError,
		arg.LastConnectionEvent,
		arg.Incrementattempts,
		arg.Setlastconnectedat,
		arg.Setlastdisconnectedat,
		arg.Setlastconnectionattemptat,
		arg.Setlastconnectionerror,
		arg.Setlastconnectionevent,
		arg.Resetattempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInstanceStatus = `-- name: UpdateInstanceStatus :execrows
UPDATE "Instance"
SET
    "connectionStatus" = $1,
    "updatedAt" = now()
WHERE "id" = $2
`

type UpdateInstanceStatusParams struct {
	Status InstanceStatus `json:"status"`
	ID     int32          `json:"id"`
}

func (q *Queries) UpdateInstanceStatus(ctx context.Context, arg UpdateInstanceStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateInstanceStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProfilePicture = `-- name: UpdateProfilePicture :execrows
WITH update_instance AS (
    UPDATE "Instance"
    SET
        "profilePicUrl" = $3,
        "updatedAt" = now()
    WHERE "id" = $1
)
INSERT INTO "InstanceWhatsAppConnection" (
    "instanceId",
    "profilePicId"
) VALUES (
    $1,
    $2
)
ON CONFLICT ("instanceId") DO UPDATE
SET
    "profilePicId" = $2,
    "updatedAt" = now()
`

type UpdateProfilePictureParams struct {
	ID            int32       `json:"id"`
	ProfilePicId  pgtype.Text `json:"profilePicId"`
	ProfilePicUrl pgtype.Text `json:"profilePicUrl"`
}

func (q *Queries) UpdateProfilePicture(ctx context.Context, arg UpdateProfilePictureParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProfilePicture, arg.ID, arg.ProfilePicId, arg.ProfilePicUrl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
