// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMessages = `-- name: CountMessages :one
SELECT count(*)
FROM "Message" m
WHERE m."instanceId" = $1
  AND (NOT $2::boolean OR m."keyId" = $3)
  AND (NOT $4::boolean OR m."keyRemoteJid" = $5)
  AND (NOT $6::boolean OR m."keyFromMe" = $7)
  AND (NOT $8::boolean OR m."messageType" = $9)
  AND (NOT $10::boolean OR m."device" = $11)
  AND (NOT $12::boolean OR m."messageTimestamp" >= $13)
  AND (NOT $14::boolean OR m."messageTimestamp" <= $15)
  AND (
      NOT $16::boolean
      OR EXISTS (
          SELECT 1
          FROM "MessageUpdate" mu
          WHERE mu."messageId" = m."id"
            AND mu."status" = $17
      )
  )
`

type CountMessagesParams struct {
	Instanceid                int32         `json:"instanceid"`
	Filterkeyid               bool          `json:"filterkeyid"`
	Keyid                     string        `json:"keyid"`
	Filterkeyremotejid        bool          `json:"filterkeyremotejid"`
	Keyremotejid              pgtype.Text   `json:"keyremotejid"`
	Filterkeyfromme           bool          `json:"filterkeyfromme"`
	Keyfromme                 bool          `json:"keyfromme"`
	Filtermessagetype         bool          `json:"filtermessagetype"`
	Messagetype               string        `json:"messagetype"`
	Filterdevice              bool          `json:"filterdevice"`
	Device                    DeviceMessage `json:"device"`
	Filtermessagetimestampgte bool          `json:"filtermessagetimestampgte"`
	Messagetimestampgte       int32         `json:"messagetimestampgte"`
	Filtermessagetimestamplte bool          `json:"filtermessagetimestamplte"`
	Messagetimestamplte       int32         `json:"messagetimestamplte"`
	Filtermessagestatus       bool          `json:"filtermessagestatus"`
	Messagestatus             string        `json:"messagestatus"`
}

func (q *Queries) CountMessages(ctx context.Context, arg CountMessagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMessages,
		arg.Instanceid,
		arg.Filterkeyid,
		arg.Keyid,
		arg.Filterkeyremotejid,
		arg.Keyremotejid,
		arg.Filterkeyfromme,
		arg.Keyfromme,
		arg.Filtermessagetype,
		arg.Messagetype,
		arg.Filterdevice,
		arg.Device,
		arg.Filtermessagetimestampgte,
		arg.Messagetimestampgte,
		arg.Filtermessagetimestamplte,
		arg.Messagetimestamplte,
		arg.Filtermessagestatus,
		arg.Messagestatus,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesBeforeID = `-- name: CountMessagesBeforeID :one
SELECT count(*)
FROM "Message" m
WHERE m."instanceId" = $1
  AND m."id" < $2
  AND (NOT $3::boolean OR m."keyId" = $4)
  AND (NOT $5::boolean OR m."keyRemoteJid" = $6)
  AND (NOT $7::boolean OR m."keyFromMe" = $8)
  AND (NOT $9::boolean OR m."messageType" = $10)
  AND (NOT $11::boolean OR m."device" = $12)
  AND (NOT $13::boolean OR m."messageTimestamp" >= $14)
  AND (NOT $15::boolean OR m."messageTimestamp" <= $16)
  AND (
      NOT $17::boolean
      OR EXISTS (
          SELECT 1
          FROM "MessageUpdate" mu
          WHERE mu."messageId" = m."id"
            AND mu."status" = $18
      )
  )
`

type CountMessagesBeforeIDParams struct {
	Instanceid                int32         `json:"instanceid"`
	ID                        int32         `json:"id"`
	Filterkeyid               bool          `json:"filterkeyid"`
	Keyid                     string        `json:"keyid"`
	Filterkeyremotejid        bool          `json:"filterkeyremotejid"`
	Keyremotejid              pgtype.Text   `json:"keyremotejid"`
	Filterkeyfromme           bool          `json:"filterkeyfromme"`
	Keyfromme                 bool          `json:"keyfromme"`
	Filtermessagetype         bool          `json:"filtermessagetype"`
	Messagetype               string        `json:"messagetype"`
	Filterdevice              bool          `json:"filterdevice"`
	Device                    DeviceMessage `json:"device"`
	Filtermessagetimestampgte bool          `json:"filtermessagetimestampgte"`
	Messagetimestampgte       int32         `json:"messagetimestampgte"`
	Filtermessagetimestamplte bool          `json:"filtermessagetimestamplte"`
	Messagetimestamplte       int32         `json:"messagetimestamplte"`
	Filtermessagestatus       bool          `json:"filtermessagestatus"`
	Messagestatus             string        `json:"messagestatus"`
}

func (q *Queries) CountMessagesBeforeID(ctx context.Context, arg CountMessagesBeforeIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesBeforeID,
		arg.Instanceid,
		arg.ID,
		arg.Filterkeyid,
		arg.Keyid,
		arg.Filterkeyremotejid,
		arg.Keyremotejid,
		arg.Filterkeyfromme,
		arg.Keyfromme,
		arg.Filtermessagetype,
		arg.Messagetype,
		arg.Filterdevice,
		arg.Device,
		arg.Filtermessagetimestampgte,
		arg.Messagetimestampgte,
		arg.Filtermessagetimestamplte,
		arg.Messagetimestamplte,
		arg.Filtermessagestatus,
		arg.Messagestatus,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO "Message" (
    "keyId",
    "keyRemoteJid",
    "keyLid",
    "keyFromMe",
    "keyParticipant",
    "keyParticipantLid",
    "pushName",
    "messageType",
    "content",
    "messageTimestamp",
    "device",
    "isGroup",
    "instanceId",
    "metadata"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING id, "keyId", "keyRemoteJid", "keyLid", "keyFromMe", "keyParticipant", "keyParticipantLid", "pushName", "messageType", content, "messageTimestamp", device, "isGroup", "instanceId", metadata
`

type CreateMessageParams struct {
	Keyid             string          `json:"keyid"`
	KeyRemoteJid      pgtype.Text     `json:"keyRemoteJid"`
	KeyLid            pgtype.Text     `json:"keyLid"`
	Keyfromme         bool            `json:"keyfromme"`
	KeyParticipant    pgtype.Text     `json:"keyParticipant"`
	KeyParticipantLid pgtype.Text     `json:"keyParticipantLid"`
	PushName          pgtype.Text     `json:"pushName"`
	Messagetype       string          `json:"messagetype"`
	Content           json.RawMessage `json:"content"`
	Messagetimestamp  int32           `json:"messagetimestamp"`
	Device            DeviceMessage   `json:"device"`
	IsGroup           pgtype.Bool     `json:"isGroup"`
	Instanceid        int32           `json:"instanceid"`
	Metadata          []byte          `json:"metadata"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.Keyid,
		arg.KeyRemoteJid,
		arg.KeyLid,
		arg.Keyfromme,
		arg.KeyParticipant,
		arg.KeyParticipantLid,
		arg.PushName,
		arg.Messagetype,
		arg.Content,
		arg.Messagetimestamp,
		arg.Device,
		arg.IsGroup,
		arg.Instanceid,
		arg.Metadata,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.KeyId,
		&i.KeyRemoteJid,
		&i.KeyLid,
		&i.KeyFromMe,
		&i.KeyParticipant,
		&i.KeyParticipantLid,
		&i.PushName,
		&i.MessageType,
		&i.Content,
		&i.MessageTimestamp,
		&i.Device,
		&i.IsGroup,
		&i.InstanceId,
		&i.Metadata,
	)
	return i, err
}

const createMessageOrIgnore = `-- name: CreateMessageOrIgnore :exec
INSERT INTO "Message" (
    "keyId",
    "keyRemoteJid",
    "keyLid",
    "keyFromMe",
    "keyParticipant",
    "keyParticipantLid",
    "pushName",
    "messageType",
    "content",
    "messageTimestamp",
    "device",
    "isGroup",
    "instanceId",
    "metadata"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
ON CONFLICT ("instanceId", "keyId") DO NOTHING
`

type CreateMessageOrIgnoreParams struct {
	Keyid             string          `json:"keyid"`
	KeyRemoteJid      pgtype.Text     `json:"keyRemoteJid"`
	KeyLid            pgtype.Text     `json:"keyLid"`
	Keyfromme         bool            `json:"keyfromme"`
	KeyParticipant    pgtype.Text     `json:"keyParticipant"`
	KeyParticipantLid pgtype.Text     `json:"keyParticipantLid"`
	PushName          pgtype.Text     `json:"pushName"`
	Messagetype       string          `json:"messagetype"`
	Content           json.RawMessage `json:"content"`
	Messagetimestamp  int32           `json:"messagetimestamp"`
	Device            DeviceMessage   `json:"device"`
	IsGroup           pgtype.Bool     `json:"isGroup"`
	Instanceid        int32           `json:"instanceid"`
	Metadata          []byte          `json:"metadata"`
}

func (q *Queries) CreateMessageOrIgnore(ctx context.Context, arg CreateMessageOrIgnoreParams) error {
	_, err := q.db.Exec(ctx, createMessageOrIgnore,
		arg.Keyid,
		arg.KeyRemoteJid,
		arg.KeyLid,
		arg.Keyfromme,
		arg.KeyParticipant,
		arg.KeyParticipantLid,
		arg.PushName,
		arg.Messagetype,
		arg.Content,
		arg.Messagetimestamp,
		arg.Device,
		arg.IsGroup,
		arg.Instanceid,
		arg.Metadata,
	)
	return err
}

const findMessageByIDForInstance = `-- name: FindMessageByIDForInstance :one
SELECT id, "keyId", "keyRemoteJid", "keyLid", "keyFromMe", "keyParticipant", "keyParticipantLid", "pushName", "messageType", content, "messageTimestamp", device, "isGroup", "instanceId", metadata
FROM "Message"
WHERE "instanceId" = $1
  AND "id" = $2
`

type FindMessageByIDForInstanceParams struct {
	Instanceid int32 `json:"instanceid"`
	ID         int32 `json:"id"`
}

func (q *Queries) FindMessageByIDForInstance(ctx context.Context, arg FindMessageByIDForInstanceParams) (Message, error) {
	row := q.db.QueryRow(ctx, findMessageByIDForInstance, arg.Instanceid, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.KeyId,
		&i.KeyRemoteJid,
		&i.KeyLid,
		&i.KeyFromMe,
		&i.KeyParticipant,
		&i.KeyParticipantLid,
		&i.PushName,
		&i.MessageType,
		&i.Content,
		&i.MessageTimestamp,
		&i.Device,
		&i.IsGroup,
		&i.InstanceId,
		&i.Metadata,
	)
	return i, err
}

const findMessageByKeyIDForInstance = `-- name: FindMessageByKeyIDForInstance :one
SELECT id, "keyId", "keyRemoteJid", "keyLid", "keyFromMe", "keyParticipant", "keyParticipantLid", "pushName", "messageType", content, "messageTimestamp", device, "isGroup", "instanceId", metadata
FROM "Message"
WHERE "instanceId" = $1
  AND "keyId" = $2
ORDER BY "id" DESC
LIMIT 1
`

type FindMessageByKeyIDForInstanceParams struct {
	Instanceid int32  `json:"instanceid"`
	Keyid      string `json:"keyid"`
}

func (q *Queries) FindMessageByKeyIDForInstance(ctx context.Context, arg FindMessageByKeyIDForInstanceParams) (Message, error) {
	row := q.db.QueryRow(ctx, findMessageByKeyIDForInstance, arg.Instanceid, arg.Keyid)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.KeyId,
		&i.KeyRemoteJid,
		&i.KeyLid,
		&i.KeyFromMe,
		&i.KeyParticipant,
		&i.KeyParticipantLid,
		&i.PushName,
		&i.MessageType,
		&i.Content,
		&i.MessageTimestamp,
		&i.Device,
		&i.IsGroup,
		&i.InstanceId,
		&i.Metadata,
	)
	return i, err
}

const findMessagesByIDsForInstance = `-- name: FindMessagesByIDsForInstance :many
SELECT id, "keyId", "keyRemoteJid", "keyLid", "keyFromMe", "keyParticipant", "keyParticipantLid", "pushName", "messageType", content, "messageTimestamp", device, "isGroup", "instanceId", metadata
FROM "Message"
WHERE "instanceId" = $1
  AND "id" = ANY($2::int[])
ORDER BY "id"
`

type FindMessagesByIDsForInstanceParams struct {
	Instanceid int32   `json:"instanceid"`
	Ids        []int32 `json:"ids"`
}

func (q *Queries) FindMessagesByIDsForInstance(ctx context.Context, arg FindMessagesByIDsForInstanceParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, findMessagesByIDsForInstance, arg.Instanceid, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.KeyId,
			&i.KeyRemoteJid,
			&i.KeyLid,
			&i.KeyFromMe,
			&i.KeyParticipant,
			&i.KeyParticipantLid,
			&i.PushName,
			&i.MessageType,
			&i.Content,
			&i.MessageTimestamp,
			&i.Device,
			&i.IsGroup,
			&i.InstanceId,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOutgoingMessageByIDForInstance = `-- name: FindOutgoingMessageByIDForInstance :one
SELECT id, "keyId", "keyRemoteJid", "keyLid", "keyFromMe", "keyParticipant", "keyParticipantLid", "pushName", "messageType", content, "messageTimestamp", device, "isGroup", "instanceId", metadata
FROM "Message"
WHERE "instanceId" = $1
  AND "id" = $2
  AND "keyFromMe" = true
`

type FindOutgoingMessageByIDForInstanceParams struct {
	Instanceid int32 `json:"instanceid"`
	ID         int32 `json:"id"`
}

func (q *Queries) FindOutgoingMessageByIDForInstance(ctx context.Context, arg FindOutgoingMessageByIDForInstanceParams) (Message, error) {
	row := q.db.QueryRow(ctx, findOutgoingMessageByIDForInstance, arg.Instanceid, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.KeyId,
		&i.KeyRemoteJid,
		&i.KeyLid,
		&i.KeyFromMe,
		&i.KeyParticipant,
		&i.KeyParticipantLid,
		&i.PushName,
		&i.MessageType,
		&i.Content,
		&i.MessageTimestamp,
		&i.Device,
		&i.IsGroup,
		&i.InstanceId,
		&i.Metadata,
	)
	return i, err
}

const findOutgoingMessageByKeyIDForInstance = `-- name: FindOutgoingMessageByKeyIDForInstance :one
SELECT id, "keyId", "keyRemoteJid", "keyLid", "keyFromMe", "keyParticipant", "keyParticipantLid", "pushName", "messageType", content, "messageTimestamp", device, "isGroup", "instanceId", metadata
FROM "Message"
WHERE "instanceId" = $1
  AND "keyId" = $2
  AND "keyFromMe" = true
ORDER BY "id" DESC
LIMIT 1
`

type FindOutgoingMessageByKeyIDForInstanceParams struct {
	Instanceid int32  `json:"instanceid"`
	Keyid      string `json:"keyid"`
}

func (q *Queries) FindOutgoingMessageByKeyIDForInstance(ctx context.Context, arg FindOutgoingMessageByKeyIDForInstanceParams) (Message, error) {
	row := q.db.QueryRow(ctx, findOutgoingMessageByKeyIDForInstance, arg.Instanceid, arg.Keyid)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.KeyId,
		&i.KeyRemoteJid,
		&i.KeyLid,
		&i.KeyFromMe,
		&i.KeyParticipant,
		&i.KeyParticipantLid,
		&i.PushName,
		&i.MessageType,
		&i.Content,
		&i.MessageTimestamp,
		&i.Device,
		&i.IsGroup,
		&i.InstanceId,
		&i.Metadata,
	)
	return i, err
}

const listMessagesNext = `-- name: ListMessagesNext :many
SELECT id, "keyId", "keyRemoteJid", "keyLid", "keyFromMe", "keyParticipant", "keyParticipantLid", "pushName", "messageType", content, "messageTimestamp", device, "isGroup", "instanceId", metadata
FROM "Message" m
WHERE m."instanceId" = $1
  AND (NOT $2::boolean OR m."id" > $3)
  AND (NOT $4::boolean OR m."keyId" = $5)
  AND (NOT $6::boolean OR m."keyRemoteJid" = $7)
  AND (NOT $8::boolean OR m."keyFromMe" = $9)
  AND (NOT $10::boolean OR m."messageType" = $11)
  AND (NOT $12::boolean OR m."device" = $13)
  AND (NOT $14::boolean OR m."messageTimestamp" >= $15)
  AND (NOT $16::boolean OR m."messageTimestamp" <= $17)
  AND (
      NOT $18::boolean
      OR EXISTS (
          SELECT 1
          FROM "MessageUpdate" mu
          WHERE mu."messageId" = m."id"
            AND mu."status" = $19
      )
  )
ORDER BY m."id"
LIMIT $20
`

type ListMessagesNextParams struct {
	Instanceid                int32         `json:"instanceid"`
	Hascursor                 bool          `json:"hascursor"`
	Cursor                    int32         `json:"cursor"`
	Filterkeyid               bool          `json:"filterkeyid"`
	Keyid                     string        `json:"keyid"`
	Filterkeyremotejid        bool          `json:"filterkeyremotejid"`
	Keyremotejid              pgtype.Text   `json:"keyremotejid"`
	Filterkeyfromme           bool          `json:"filterkeyfromme"`
	Keyfromme                 bool          `json:"keyfromme"`
	Filtermessagetype         bool          `json:"filtermessagetype"`
	Messagetype               string        `json:"messagetype"`
	Filterdevice              bool          `json:"filterdevice"`
	Device                    DeviceMessage `json:"device"`
	Filtermessagetimestampgte bool          `json:"filtermessagetimestampgte"`
	Messagetimestampgte       int32         `json:"messagetimestampgte"`
	Filtermessagetimestamplte bool          `json:"filtermessagetimestamplte"`
	Messagetimestamplte       int32         `json:"messagetimestamplte"`
	Filtermessagestatus       bool          `json:"filtermessagestatus"`
	Messagestatus             string        `json:"messagestatus"`
	Limitcount                int32         `json:"limitcount"`
}

func (q *Queries) ListMessagesNext(ctx context.Context, arg ListMessagesNextParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesNext,
		arg.Instanceid,
		arg.Hascursor,
		arg.Cursor,
		arg.Filterkeyid,
		arg.Keyid,
		arg.Filterkeyremotejid,
		arg.Keyremotejid,
		arg.Filterkeyfromme,
		arg.Keyfromme,
		arg.Filtermessagetype,
		arg.Messagetype,
		arg.Filterdevice,
		arg.Device,
		arg.Filtermessagetimestampgte,
		arg.Messagetimestampgte,
		arg.Filtermessagetimestamplte,
		arg.Messagetimestamplte,
		arg.Filtermessagestatus,
		arg.Messagestatus,
		arg.Limitcount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.KeyId,
			&i.KeyRemoteJid,
			&i.KeyLid,
			&i.KeyFromMe,
			&i.KeyParticipant,
			&i.KeyParticipantLid,
			&i.PushName,
			&i.MessageType,
			&i.Content,
			&i.MessageTimestamp,
			&i.Device,
			&i.IsGroup,
			&i.InstanceId,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesPrevious = `-- name: ListMessagesPrevious :many
SELECT id, "keyId", "keyRemoteJid", "keyLid", "keyFromMe", "keyParticipant", "keyParticipantLid", "pushName", "messageType", content, "messageTimestamp", device, "isGroup", "instanceId", metadata
FROM "Message" m
WHERE m."instanceId" = $1
  AND (NOT $2::boolean OR m."id" < $3)
  AND (NOT $4::boolean OR m."keyId" = $5)
  AND (NOT $6::boolean OR m."keyRemoteJid" = $7)
  AND (NOT $8::boolean OR m."keyFromMe" = $9)
  AND (NOT $10::boolean OR m."messageType" = $11)
  AND (NOT $12::boolean OR m."device" = $13)
  AND (NOT $14::boolean OR m."messageTimestamp" >= $15)
  AND (NOT $16::boolean OR m."messageTimestamp" <= $17)
  AND (
      NOT $18::boolean
      OR EXISTS (
          SELECT 1
          FROM "MessageUpdate" mu
          WHERE mu."messageId" = m."id"
            AND mu."status" = $19
      )
  )
ORDER BY m."id" DESC
LIMIT $20
`

type ListMessagesPreviousParams struct {
	Instanceid                int32         `json:"instanceid"`
	Hascursor                 bool          `json:"hascursor"`
	Cursor                    int32         `json:"cursor"`
	Filterkeyid               bool          `json:"filterkeyid"`
	Keyid                     string        `json:"keyid"`
	Filterkeyremotejid        bool          `json:"filterkeyremotejid"`
	Keyremotejid              pgtype.Text   `json:"keyremotejid"`
	Filterkeyfromme           bool          `json:"filterkeyfromme"`
	Keyfromme                 bool          `json:"keyfromme"`
	Filtermessagetype         bool          `json:"filtermessagetype"`
	Messagetype               string        `json:"messagetype"`
	Filterdevice              bool          `json:"filterdevice"`
	Device                    DeviceMessage `json:"device"`
	Filtermessagetimestampgte bool          `json:"filtermessagetimestampgte"`
	Messagetimestampgte       int32         `json:"messagetimestampgte"`
	Filtermessagetimestamplte bool          `json:"filtermessagetimestamplte"`
	Messagetimestamplte       int32         `json:"messagetimestamplte"`
	Filtermessagestatus       bool          `json:"filtermessagestatus"`
	Messagestatus             string        `json:"messagestatus"`
	Limitcount                int32         `json:"limitcount"`
}

func (q *Queries) ListMessagesPrevious(ctx context.Context, arg ListMessagesPreviousParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesPrevious,
		arg.Instanceid,
		arg.Hascursor,
		arg.Cursor,
		arg.Filterkeyid,
		arg.Keyid,
		arg.Filterkeyremotejid,
		arg.Keyremotejid,
		arg.Filterkeyfromme,
		arg.Keyfromme,
		arg.Filtermessagetype,
		arg.Messagetype,
		arg.Filterdevice,
		arg.Device,
		arg.Filtermessagetimestampgte,
		arg.Messagetimestampgte,
		arg.Filtermessagetimestamplte,
		arg.Messagetimestamplte,
		arg.Filtermessagestatus,
		arg.Messagestatus,
		arg.Limitcount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.KeyId,
			&i.KeyRemoteJid,
			&i.KeyLid,
			&i.KeyFromMe,
			&i.KeyParticipant,
			&i.KeyParticipantLid,
			&i.PushName,
			&i.MessageType,
			&i.Content,
			&i.MessageTimestamp,
			&i.Device,
			&i.IsGroup,
			&i.InstanceId,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessagesReadForInstance = `-- name: MarkMessagesReadForInstance :execrows
INSERT INTO "MessageUpdate" (
    "dateTime",
    "status",
    "messageId"
)
SELECT
    $1,
    'READ',
    m."id"
FROM "Message" m
WHERE m."instanceId" = $2
  AND m."id" = ANY($3::int[])
`

type MarkMessagesReadForInstanceParams struct {
	Datetime   pgtype.Timestamp `json:"datetime"`
	Instanceid int32            `json:"instanceid"`
	Ids        []int32          `json:"ids"`
}

func (q *Queries) MarkMessagesReadForInstance(ctx context.Context, arg MarkMessagesReadForInstanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMessagesReadForInstance, arg.Datetime, arg.Instanceid, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const messageExists = `-- name: MessageExists :one
SELECT EXISTS (
    SELECT 1
    FROM "Message"
    WHERE "id" = $1
) AS "exists"
`

func (q *Queries) MessageExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, messageExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateMessageContentForInstance = `-- name: UpdateMessageContentForInstance :one
UPDATE "Message"
SET "content" = $1
WHERE "instanceId" = $2
  AND "id" = $3
RETURNING id, "keyId", "keyRemoteJid", "keyLid", "keyFromMe", "keyParticipant", "keyParticipantLid", "pushName", "messageType", content, "messageTimestamp", device, "isGroup", "instanceId", metadata
`

type UpdateMessageContentForInstanceParams struct {
	Content    json.RawMessage `json:"content"`
	Instanceid int32           `json:"instanceid"`
	ID         int32           `json:"id"`
}

func (q *Queries) UpdateMessageContentForInstance(ctx context.Context, arg UpdateMessageContentForInstanceParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageContentForInstance, arg.Content, arg.Instanceid, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.KeyId,
		&i.KeyRemoteJid,
		&i.KeyLid,
		&i.KeyFromMe,
		&i.KeyParticipant,
		&i.KeyParticipantLid,
		&i.PushName,
		&i.MessageType,
		&i.Content,
		&i.MessageTimestamp,
		&i.Device,
		&i.IsGroup,
		&i.InstanceId,
		&i.Metadata,
	)
	return i, err
}
