// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message_update.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessageUpdate = `-- name: CreateMessageUpdate :one
INSERT INTO "MessageUpdate" (
    "dateTime",
    "status",
    "messageId"
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, "dateTime", status, "messageId"
`

type CreateMessageUpdateParams struct {
	Datetime  pgtype.Timestamp `json:"datetime"`
	Status    string           `json:"status"`
	Messageid int32            `json:"messageid"`
}

func (q *Queries) CreateMessageUpdate(ctx context.Context, arg CreateMessageUpdateParams) (MessageUpdate, error) {
	row := q.db.QueryRow(ctx, createMessageUpdate, arg.Datetime, arg.Status, arg.Messageid)
	var i MessageUpdate
	err := row.Scan(
		&i.ID,
		&i.DateTime,
		&i.Status,
		&i.MessageId,
	)
	return i, err
}

const createMessageUpdateOrIgnore = `-- name: CreateMessageUpdateOrIgnore :exec
INSERT INTO "MessageUpdate" (
    "dateTime",
    "status",
    "messageId"
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT ("messageId", "status", "dateTime") DO NOTHING
`

type CreateMessageUpdateOrIgnoreParams struct {
	Datetime  pgtype.Timestamp `json:"datetime"`
	Status    string           `json:"status"`
	Messageid int32            `json:"messageid"`
}

func (q *Queries) CreateMessageUpdateOrIgnore(ctx context.Context, arg CreateMessageUpdateOrIgnoreParams) error {
	_, err := q.db.Exec(ctx, createMessageUpdateOrIgnore, arg.Datetime, arg.Status, arg.Messageid)
	return err
}

const listMessageUpdatesByMessageID = `-- name: ListMessageUpdatesByMessageID :many
SELECT id, "dateTime", status, "messageId"
FROM "MessageUpdate"
WHERE "messageId" = $1
ORDER BY "dateTime", "id"
`

func (q *Queries) ListMessageUpdatesByMessageID(ctx context.Context, messageid int32) ([]MessageUpdate, error) {
	rows, err := q.db.Query(ctx, listMessageUpdatesByMessageID, messageid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageUpdate
	for rows.Next() {
		var i MessageUpdate
		if err := rows.Scan(
			&i.ID,
			&i.DateTime,
			&i.Status,
			&i.MessageId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageUpdatesByMessageIDs = `-- name: ListMessageUpdatesByMessageIDs :many
SELECT id, "dateTime", status, "messageId"
FROM "MessageUpdate"
WHERE "messageId" = ANY($1::int[])
ORDER BY "messageId", "dateTime", "id"
`

func (q *Queries) ListMessageUpdatesByMessageIDs(ctx context.Context, messageids []int32) ([]MessageUpdate, error) {
	rows, err := q.db.Query(ctx, listMessageUpdatesByMessageIDs, messageids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageUpdate
	for rows.Next() {
		var i MessageUpdate
		if err := rows.Scan(
			&i.ID,
			&i.DateTime,
			&i.Status,
			&i.MessageId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
