// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DeviceMessage string

const (
	DeviceMessageIos     DeviceMessage = "ios"
	DeviceMessageAndroid DeviceMessage = "android"
	DeviceMessageWeb     DeviceMessage = "web"
	DeviceMessageUnknown DeviceMessage = "unknown"
	DeviceMessageDesktop DeviceMessage = "desktop"
)

func (e *DeviceMessage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceMessage(s)
	case string:
		*e = DeviceMessage(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceMessage: %T", src)
	}
	return nil
}

type NullDeviceMessage struct {
	DeviceMessage DeviceMessage `json:"DeviceMessage"`
	Valid         bool          `json:"valid"` // Valid is true if DeviceMessage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceMessage) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceMessage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceMessage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceMessage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceMessage), nil
}

type InstanceStatus string

const (
	InstanceStatusONLINE  InstanceStatus = "ONLINE"
	InstanceStatusOFFLINE InstanceStatus = "OFFLINE"
)

func (e *InstanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InstanceStatus(s)
	case string:
		*e = InstanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InstanceStatus: %T", src)
	}
	return nil
}

type NullInstanceStatus struct {
	InstanceStatus InstanceStatus `json:"InstanceStatus"`
	Valid          bool           `json:"valid"` // Valid is true if InstanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInstanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InstanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InstanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInstanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InstanceStatus), nil
}

type Auth struct {
	ID         int32            `json:"id"`
	Token      string           `json:"token"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
	InstanceId int32            `json:"instanceId"`
}

type Chat struct {
	ID         int32            `json:"id"`
	RemoteJid  string           `json:"remoteJid"`
	Content    []byte           `json:"content"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
	InstanceId int32            `json:"instanceId"`
}

type Contact struct {
	ID            int32            `json:"id"`
	RemoteJid     string           `json:"remoteJid"`
	PushName      pgtype.Text      `json:"pushName"`
	ProfilePicUrl pgtype.Text      `json:"profilePicUrl"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	UpdatedAt     pgtype.Timestamp `json:"updatedAt"`
	InstanceId    int32            `json:"instanceId"`
}

type Instance struct {
	ID                 int32            `json:"id"`
	Name               string           `json:"name"`
	Description        pgtype.Text      `json:"description"`
	ConnectionStatus   InstanceStatus   `json:"connectionStatus"`
	OwnerJid           pgtype.Text      `json:"ownerJid"`
	ProfilePicUrl      pgtype.Text      `json:"profilePicUrl"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
	UpdatedAt          pgtype.Timestamp `json:"updatedAt"`
	ExternalAttributes []byte           `json:"externalAttributes"`
}

type InstanceWhatsAppConnection struct {
	InstanceId              int32            `json:"instanceId"`
	ConnectionStatus        string           `json:"connectionStatus"`
	WhatsappDeviceJid       pgtype.Text      `json:"whatsappDeviceJid"`
	WhatsappOwnerJid        pgtype.Text      `json:"whatsappOwnerJid"`
	WhatsappPhoneNumber     pgtype.Text      `json:"whatsappPhoneNumber"`
	ProfilePicId            pgtype.Text      `json:"profilePicId"`
	LastConnectedAt         pgtype.Timestamp `json:"lastConnectedAt"`
	LastDisconnectedAt      pgtype.Timestamp `json:"lastDisconnectedAt"`
	LastConnectionAttemptAt pgtype.Timestamp `json:"lastConnectionAttemptAt"`
	LastConnectionError     pgtype.Text      `json:"lastConnectionError"`
	LastConnectionEvent     pgtype.Text      `json:"lastConnectionEvent"`
	ConnectionAttempts      int32            `json:"connectionAttempts"`
	CreatedAt               pgtype.Timestamp `json:"createdAt"`
	UpdatedAt               pgtype.Timestamp `json:"updatedAt"`
}

type Message struct {
	ID                int32           `json:"id"`
	KeyId             string          `json:"keyId"`
	KeyRemoteJid      pgtype.Text     `json:"keyRemoteJid"`
	KeyLid            pgtype.Text     `json:"keyLid"`
	KeyFromMe         bool            `json:"keyFromMe"`
	KeyParticipant    pgtype.Text     `json:"keyParticipant"`
	KeyParticipantLid pgtype.Text     `json:"keyParticipantLid"`
	PushName          pgtype.Text     `json:"pushName"`
	MessageType       string          `json:"messageType"`
	Content           json.RawMessage `json:"content"`
	MessageTimestamp  int32           `json:"messageTimestamp"`
	Device            DeviceMessage   `json:"device"`
	IsGroup           pgtype.Bool     `json:"isGroup"`
	InstanceId        int32           `json:"instanceId"`
	Metadata          []byte          `json:"metadata"`
}

type MessageUpdate struct {
	ID        int32            `json:"id"`
	DateTime  pgtype.Timestamp `json:"dateTime"`
	Status    string           `json:"status"`
	MessageId int32            `json:"messageId"`
}

type Webhook struct {
	ID         int32            `json:"id"`
	Url        string           `json:"url"`
	Enabled    bool             `json:"enabled"`
	Events     []byte           `json:"events"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
	InstanceId int32            `json:"instanceId"`
}

type WhatsAppAddressMapping struct {
	InstanceId      int32            `json:"instanceId"`
	Alias           string           `json:"alias"`
	NormalizedPhone string           `json:"normalizedPhone"`
	CanonicalJid    string           `json:"canonicalJid"`
	LidJid          pgtype.Text      `json:"lidJid"`
	ResolvedAt      pgtype.Timestamp `json:"resolvedAt"`
	ExpiresAt       pgtype.Timestamp `json:"expiresAt"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	UpdatedAt       pgtype.Timestamp `json:"updatedAt"`
}
