// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhook.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearWebhookEvents = `-- name: ClearWebhookEvents :one
UPDATE "Webhook"
SET
    "events" = '{}'::jsonb,
    "updatedAt" = now()
WHERE "id" = $1
RETURNING id, url, enabled, events, "createdAt", "updatedAt", "instanceId"
`

func (q *Queries) ClearWebhookEvents(ctx context.Context, id int32) (Webhook, error) {
	row := q.db.QueryRow(ctx, clearWebhookEvents, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Enabled,
		&i.Events,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceId,
	)
	return i, err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO "Webhook" (
    "url",
    "enabled",
    "events",
    "instanceId"
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, url, enabled, events, "createdAt", "updatedAt", "instanceId"
`

type CreateWebhookParams struct {
	Url        string `json:"url"`
	Enabled    bool   `json:"enabled"`
	Events     []byte `json:"events"`
	Instanceid int32  `json:"instanceid"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.Url,
		arg.Enabled,
		arg.Events,
		arg.Instanceid,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Enabled,
		&i.Events,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceId,
	)
	return i, err
}

const findWebhookByInstanceName = `-- name: FindWebhookByInstanceName :one
SELECT w.id, w.url, w.enabled, w.events, w."createdAt", w."updatedAt", w."instanceId"
FROM "Webhook" w
JOIN "Instance" i ON i."id" = w."instanceId"
WHERE i."name" = $1
`

func (q *Queries) FindWebhookByInstanceName(ctx context.Context, instancename string) (Webhook, error) {
	row := q.db.QueryRow(ctx, findWebhookByInstanceName, instancename)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Enabled,
		&i.Events,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceId,
	)
	return i, err
}

const listEnabledWebhooksWithInstance = `-- name: ListEnabledWebhooksWithInstance :many
SELECT
    w."id",
    w."url",
    w."enabled",
    w."events",
    w."createdAt",
    w."updatedAt",
    w."instanceId",
    i."name" AS "instanceName"
FROM "Webhook" w
JOIN "Instance" i ON i."id" = w."instanceId"
WHERE w."enabled" = true
ORDER BY w."id"
`

type ListEnabledWebhooksWithInstanceRow struct {
	ID           int32            `json:"id"`
	Url          string           `json:"url"`
	Enabled      bool             `json:"enabled"`
	Events       []byte           `json:"events"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
	InstanceId   int32            `json:"instanceId"`
	InstanceName string           `json:"instanceName"`
}

func (q *Queries) ListEnabledWebhooksWithInstance(ctx context.Context) ([]ListEnabledWebhooksWithInstanceRow, error) {
	rows, err := q.db.Query(ctx, listEnabledWebhooksWithInstance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledWebhooksWithInstanceRow
	for rows.Next() {
		var i ListEnabledWebhooksWithInstanceRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Enabled,
			&i.Events,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstanceId,
			&i.InstanceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeWebhookEvents = `-- name: MergeWebhookEvents :one
UPDATE "Webhook"
SET
    "events" = COALESCE("events", '{}'::jsonb) || $1::jsonb,
    "updatedAt" = now()
WHERE "id" = $2
RETURNING id, url, enabled, events, "createdAt", "updatedAt", "instanceId"
`

type MergeWebhookEventsParams struct {
	Events json.RawMessage `json:"events"`
	ID     int32           `json:"id"`
}

func (q *Queries) MergeWebhookEvents(ctx context.Context, arg MergeWebhookEventsParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, mergeWebhookEvents, arg.Events, arg.ID)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Enabled,
		&i.Events,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceId,
	)
	return i, err
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE "Webhook"
SET
    "url" = CASE WHEN $1::boolean THEN $2 ELSE "url" END,
    "enabled" = CASE WHEN $3::boolean THEN $4 ELSE "enabled" END,
    "updatedAt" = now()
WHERE "id" = $5
RETURNING id, url, enabled, events, "createdAt", "updatedAt", "instanceId"
`

type UpdateWebhookParams struct {
	Seturl     bool   `json:"seturl"`
	Url        string `json:"url"`
	Setenabled bool   `json:"setenabled"`
	Enabled    bool   `json:"enabled"`
	ID         int32  `json:"id"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.Seturl,
		arg.Url,
		arg.Setenabled,
		arg.Enabled,
		arg.ID,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Enabled,
		&i.Events,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstanceId,
	)
	return i, err
}
